name: Website Deploy

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      -
        name: Checkout Code
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - 
        name: Setup Node
        uses: actions/setup-node@v2.4.0
        with:
          node-version: "16"
      - 
        name: Setup Dependencies
        run: yarn install
          
      - 
        name: Build Site
        run: yarn build
        
      - 
        name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.2.2
        with: 
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: ./dist